[Telegram]
# no need for quotes

# you can get telegram development credentials in telegram API Development Tools
api_id = 2890794
api_hash = 2bdb9961bdb3ea6c32796e7da2aae111

# use full phone number including + and country code
phone = +989375169745
username = exb

